export type TrekGrade = 'grade-easy' | 'grade-mod' | 'grade-hard';

export interface TrekStat {
  value: string;
  label: string;
}

export interface ItineraryStep {
  day: string;
  title: string;
  body: string;
}

export interface Trek {
  slug: string;
  title: string;
  region: string;
  lat?: number;
  lng?: number;
  grade: TrekGrade;
  gradeLabel: string;
  image: string;
  imageAlt: string;
  images: string[];
  imageCredit?: string;
  distanceKm?: string;
  cardStats: TrekStat[];
  detailStats: TrekStat[];
  desc: string;
  note: string;
  itineraryHeading?: string;
  itineraryEyebrow?: string;
  itineraryNote?: string;
  itinerary: ItineraryStep[];
  durationDays?: number;
  maxAltitudeM?: number;
  season?: string;
  batchDates?: string[];
  included?: string[];
  excluded?: string[];
}

const DEFAULT_INCLUDED = [
  'Camping & stay through the trek',
  'All meals from Day 1 dinner to the last breakfast',
  'Trek permits & forest fees',
  'Experienced trek leader & support crew',
  'First-aid kit & daily oximeter checks',
];

const DEFAULT_EXCLUDED = [
  'Transport to/from the base village',
  'Personal trekking gear (rentable on request)',
  'Travel insurance',
  'Anything outside the day-by-day itinerary',
];

export const TREKS: Record<string, Trek> = {
  kedarkantha: {
    slug: 'kedarkantha',
    title: 'Kedarkantha',
    region: 'Uttarakhand · Govind Wildlife Sanctuary',
    lat: 31.05,
    lng: 78.25,
    grade: 'grade-easy',
    gradeLabel: 'Easy – Moderate',
    image: 'images/kedarkantha-region.jpg',
    imageAlt: 'Snow-covered Himalayan valley near Sankri, the Kedarkantha trailhead',
    images: [
      'images/kedarkantha-region.jpg',
      'images/kedarkantha-harkidun.jpg',
      'images/kedarkantha-supin-valley.jpg',
    ],
    distanceKm: '~20 km',
    cardStats: [
      { value: '3800m', label: 'Summit alt.' },
      { value: '5D / 4N', label: 'Duration' },
      { value: 'Dec–Apr', label: 'Season' },
    ],
    detailStats: [
      { value: '3800m', label: 'Summit alt.' },
      { value: '5D / 4N', label: 'Duration' },
      { value: 'Dec–Apr', label: 'Season' },
    ],
    desc: 'A snow-guaranteed winter summit and the most reliable first Himalayan trek we run — forest camps, a frozen lake at Juda Ka Talab, then a ridge walk to a 360° summit.',
    note: 'Next batch forming · DM @trekwith_g',
    durationDays: 5,
    maxAltitudeM: 3800,
    season: 'Dec–Apr',
    batchDates: ['Dec 12–16, 2026', 'Jan 9–13, 2027', 'Feb 13–17, 2027'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Sankri → Juda Ka Talab', body: 'A steady 4 km climb out of Sankri through oak and pine forest to a frozen lake campsite at roughly 3,350m.' },
      { day: 'Day 2', title: 'Juda Ka Talab → Kedarkantha Base', body: 'A short, deliberately easy 4 km day so the group acclimatizes before the summit push. Camp sits right at the treeline with the first clear view of the summit ridge.' },
      { day: 'Day 3', title: 'Base → Summit (3,800m) → Hargaon', body: 'Pre-dawn start for the ridge walk and 360° summit, then a long ~10 km descent to a lower, warmer camp the same day.' },
      { day: 'Day 4', title: 'Hargaon → Sankri', body: 'Easy 6 km descent back through forest to the roadhead.' },
      { day: 'Day 5', title: 'Buffer day', body: 'Held in reserve for weather or pace — used for the drive back to Dehradun if the trail runs on schedule.' },
    ],
  },
  'hampta-pass': {
    slug: 'hampta-pass',
    title: 'Hampta Pass',
    region: 'Himachal Pradesh · Kullu–Lahaul crossing',
    lat: 32.24,
    lng: 77.28,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/hampta-pass.jpg',
    imageAlt: 'Hampta Pass ridgeline, Himachal Pradesh',
    images: [
      'images/hampta-pass.jpg',
      'images/hampta-shepherd.jpg',
      'images/hampta-chandratal.jpg',
    ],
    distanceKm: '~26 km',
    cardStats: [
      { value: '4287m', label: 'Pass alt.' },
      { value: '5D / 4N', label: 'Duration' },
      { value: 'Jun–Oct', label: 'Season' },
    ],
    detailStats: [
      { value: '4287m', label: 'Pass alt.' },
      { value: '5D / 4N', label: 'Duration' },
      { value: 'Jun–Oct', label: 'Season' },
    ],
    desc: 'Crosses from pine-forest Kullu into the stark brown Lahaul valley in one pass — the most dramatic landscape shift of any short trek we lead. Often paired with a Chandratal add-on.',
    note: 'Next batch forming · DM @trekwith_g',
    durationDays: 5,
    maxAltitudeM: 4287,
    season: 'Jun–Oct',
    batchDates: ['Sep 25–29, 2026', 'Oct 9–13, 2026'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Jobra → Chika', body: 'A short 3 km walk-in from the roadhead. First night camped by the Rani nallah.' },
      { day: 'Day 2', title: 'Chika → Balu Ka Ghera', body: 'A 7 km climb via Jwara into high meadows, camping right under the pass with the first big peak views.' },
      { day: 'Day 3', title: 'Balu Ka Ghera → Hampta Pass (4,287m) → Shea Goru', body: 'The crossing day: steep to the pass, then a dramatic ~9 km drop into the stark Lahaul valley.' },
      { day: 'Day 4', title: 'Shea Goru → Chatru', body: 'Descend roughly 10 km to the road. Groups doing the Chandratal extension continue by vehicle to the lake for the night.' },
      { day: 'Day 5', title: 'Chatru / Chandratal → Manali', body: 'Return drive over Rohtang / the Atal Tunnel back to Manali.' },
    ],
  },
  'valley-of-flowers': {
    slug: 'valley-of-flowers',
    title: 'Valley of Flowers',
    region: 'Uttarakhand · UNESCO World Heritage Site',
    lat: 30.729,
    lng: 79.605,
    grade: 'grade-easy',
    gradeLabel: 'Easy – Moderate',
    image: 'images/valley-of-flowers.jpg',
    imageAlt: 'Valley of Flowers National Park in full monsoon bloom',
    images: [
      'images/valley-of-flowers.jpg',
      'images/valley-of-flowers-bloom.jpg',
      'images/vof-hemkund-sahib.jpg',
    ],
    distanceKm: '~38 km',
    cardStats: [
      { value: '3658m', label: 'Valley alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    detailStats: [
      { value: '3658m', label: 'Valley alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    desc: "A monsoon-only window when the alpine meadow floods with 600+ flowering species — Himalayan blue poppy, cobra lily, wild orchids. Slow-paced by design, this one's about the valley floor, not a summit.",
    note: 'Next batch forming · DM @trekwith_g',
    durationDays: 6,
    maxAltitudeM: 3658,
    season: 'Jul–Sep',
    batchDates: ['Jul 10–15, 2027', 'Aug 7–12, 2027'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Govindghat/Pulna → Ghangaria', body: 'The main trekking day, roughly 9–13 km up the Pushpawati valley to the basecamp village.' },
      { day: 'Day 2', title: 'Ghangaria → Valley of Flowers → Ghangaria', body: 'A full, slow-paced day inside the national park — an 8 km round trip through the bloom.' },
      { day: 'Day 3', title: 'Ghangaria → Hemkund Sahib → Ghangaria', body: 'A steep 12 km round trip to the glacial lake and gurudwara at 4,329m, weather permitting.' },
      { day: 'Day 4', title: 'Ghangaria → Govindghat/Pulna', body: 'Return descent to the roadhead.' },
      { day: 'Day 5', title: 'Buffer day', body: 'Held in reserve for weather at Hemkund or delayed road access.' },
      { day: 'Day 6', title: 'Departure', body: 'Onward drive from Govindghat / Joshimath.' },
    ],
  },
  chadar: {
    slug: 'chadar',
    title: 'Chadar',
    region: 'Ladakh · Frozen Zanskar river',
    lat: 34.05,
    lng: 77.35,
    grade: 'grade-hard',
    gradeLabel: 'Strenuous · Expedition',
    image: 'images/chadar-zanskar.jpg',
    imageAlt: 'Trekkers on the frozen Zanskar river, Chadar trek, Ladakh',
    images: [
      'images/chadar-zanskar.jpg',
      'images/chadar-trek-01.jpg',
      'images/chadar-trek-14.jpg',
    ],
    distanceKm: '~85 km',
    cardStats: [
      { value: '3850m', label: 'Max alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'Jan–Feb', label: 'Season' },
    ],
    detailStats: [
      { value: '3850m', label: 'Max alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'Jan–Feb', label: 'Season' },
    ],
    desc: "You walk on the river itself. Sub-zero nights in caves, ice that cracks underfoot, temperatures down to −20°C, and a support crew that's walked this route more times than anyone should. Our most demanding departure.",
    note: 'Limited to 12 trekkers · DM @trekwith_g',
    durationDays: 8,
    maxAltitudeM: 3850,
    season: 'Jan–Feb',
    batchDates: ['Jan 15–22, 2027', 'Feb 5–12, 2027'],
    included: [...DEFAULT_INCLUDED, 'Wilderness Institute / Leh permits', 'Standby oxygen cylinder & cave camps'],
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Arrive Leh', body: 'A full rest day at altitude before any trekking begins — non-negotiable at 3,500m.' },
      { day: 'Day 2', title: 'Leh → Chilling → Shingra Koma', body: 'Drive to the Zanskar confluence, then the first steps onto the Chadar itself.' },
      { day: 'Day 3', title: 'Shingra Koma → Tibb Cave', body: 'A full ~10 km day on the ice, camping in a natural cave used by trekkers for decades.' },
      { day: 'Day 4', title: 'Tibb Cave → Naerak', body: 'Deeper into the gorge, roughly 10–12 km, past the frozen Naerak waterfall.' },
      { day: 'Day 5', title: 'Naerak — turnaround point', body: 'Rest and acclimatize; this is as far as our standard batch goes before starting back.' },
      { day: 'Day 6', title: 'Naerak → Tibb Cave', body: 'Retrace the route back down the frozen river.' },
      { day: 'Day 7', title: 'Tibb Cave → Shingra Koma / Chilling', body: 'Back off the ice and to the roadhead.' },
      { day: 'Day 8', title: 'Drive to Leh, departure', body: 'Buffer built in for ice conditions; used as a rest day if the trek ran to schedule.' },
    ],
  },
  brahmatal: {
    slug: 'brahmatal',
    title: 'Brahmatal',
    region: 'Uttarakhand · Alpine lake circuit',
    lat: 30.28,
    lng: 79.75,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/brahmatal-campsite.jpg',
    imageAlt: 'Snow campsite on the Brahmatal trek, Uttarakhand',
    images: [
      'images/brahmatal-campsite.jpg',
      'images/brahmatal-nandaghunti-view.jpg',
      'images/brahmatal-trekker-view.jpg',
    ],
    distanceKm: '~26 km',
    cardStats: [
      { value: '3734m', label: 'Summit alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Dec–Apr', label: 'Season' },
    ],
    detailStats: [
      { value: '3734m', label: 'Summit alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Dec–Apr', label: 'Season' },
    ],
    desc: 'A winter ridge walk with views of Trishul and Nanda Ghunti most days — and a frozen lake camp that rarely makes it into the usual trek lists.',
    note: 'Next batch forming · DM @trekwith_g',
    durationDays: 6,
    maxAltitudeM: 3734,
    season: 'Dec–Apr',
    batchDates: ['Dec 19–24, 2026', 'Jan 16–21, 2027'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Lohajung → Bekaltal', body: 'A gentle 5 km forest walk to a small lake camp.' },
      { day: 'Day 2', title: 'Bekaltal → Brahmatal Base', body: 'A 6 km ridge walk with the first big views of Trishul and Nanda Ghunti.' },
      { day: 'Day 3', title: 'Base → Brahmatal Summit (3,734m) → Daldum', body: 'Dawn summit push, then descend roughly 8–9 km to a lower camp the same day.' },
      { day: 'Day 4', title: 'Daldum → Lohajung', body: 'A 7 km descent back to the roadhead.' },
      { day: 'Day 5', title: 'Buffer day', body: 'Reserve for weather or an easier pace on snow.' },
      { day: 'Day 6', title: 'Departure from Lohajung', body: 'Onward drive to Kathgodam or Rishikesh.' },
    ],
  },
  triund: {
    slug: 'triund',
    title: 'Triund',
    region: 'Himachal Pradesh · Dhauladhar range, McLeod Ganj',
    lat: 32.249,
    lng: 76.32,
    grade: 'grade-easy',
    gradeLabel: 'Easy',
    image: 'images/triund-night-camp.jpg',
    imageAlt: 'Tents pitched at the Triund campsite under a clear night sky, Dhauladhar range',
    images: ['images/triund-night-camp.jpg'],
    distanceKm: '~18 km',
    cardStats: [
      { value: '2975m', label: 'Ridge alt.' },
      { value: '2D / 1N', label: 'Duration' },
      { value: 'Oct–Jun', label: 'Season' },
    ],
    detailStats: [
      { value: '2975m', label: 'Ridge alt.' },
      { value: '2D / 1N', label: 'Duration' },
      { value: 'Oct–Jun', label: 'Season' },
    ],
    desc: 'The easiest real Himalayan view we sell — a steep half-day climb out of McLeod Ganj to a ridge camp staring straight at the Dhauladhar wall. Good first overnight for anyone unsure they even like camping.',
    note: 'Next batch forming · DM @trekwith_g',
    durationDays: 2,
    maxAltitudeM: 2975,
    season: 'Oct–Jun',
    batchDates: ['Nov 7–8, 2026', 'Dec 5–6, 2026', 'Apr 10–11, 2027'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'McLeod Ganj → Triund', body: 'A steep ~9 km climb through oak and rhododendron forest, gaining most of the altitude in the last hour. Camp is pitched right on the ridge facing the Dhauladhar wall.' },
      { day: 'Day 2', title: 'Triund → McLeod Ganj', body: 'Sunrise over the snowline, then the same ~9 km back down — knees will know about it by the bottom.' },
    ],
  },
  'har-ki-dun': {
    slug: 'har-ki-dun',
    title: 'Har Ki Dun',
    region: 'Uttarakhand · Govind Wildlife Sanctuary',
    lat: 31.05,
    lng: 78.197,
    grade: 'grade-easy',
    gradeLabel: 'Easy – Moderate',
    image: 'images/kedarkantha-supin-valley.jpg',
    imageAlt: 'Supin valley near Sankri, the shared trailhead for Har Ki Dun and Kedarkantha',
    images: ['images/kedarkantha-supin-valley.jpg'],
    distanceKm: '~47 km',
    cardStats: [
      { value: '3566m', label: 'Valley alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Mar–Jun, Sep–Dec', label: 'Season' },
    ],
    detailStats: [
      { value: '3566m', label: 'Valley alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Mar–Jun, Sep–Dec', label: 'Season' },
    ],
    desc: 'A wide, gentle valley trek out of the same Sankri roadhead as Kedarkantha, ending under the Swargarohini peaks in a village that local legend ties to the Mahabharata. Long days, but nothing technical.',
    note: 'Next batch forming · DM @trekwith_g',
    durationDays: 6,
    maxAltitudeM: 3566,
    season: 'Mar–Jun, Sep–Dec',
    batchDates: ['May 14–19, 2027', 'Oct 8–13, 2027'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Sankri → Taluka → Osla', body: 'A drive to Taluka, then an ~12 km riverside walk through the Supin valley to the wood-carved village of Osla.' },
      { day: 'Day 2', title: 'Osla → Har Ki Dun', body: 'A steady ~12 km climb up the valley, tree line giving way to open meadow at the Har Ki Dun campsite.' },
      { day: 'Day 3', title: 'Har Ki Dun → Jaundhar Glacier viewpoint → Har Ki Dun', body: 'A rest-paced ~8 km round trip further up the valley toward the glacier, with the Swargarohini peaks close overhead.' },
      { day: 'Day 4', title: 'Har Ki Dun → Osla', body: 'Retrace the ~12 km descent back to Osla.' },
      { day: 'Day 5', title: 'Osla → Taluka → Sankri', body: 'Walk out to Taluka, then drive back to Sankri.' },
      { day: 'Day 6', title: 'Buffer / departure', body: 'Held in reserve for weather; used for the drive back to Dehradun if the trail ran on schedule.' },
    ],
  },
  roopkund: {
    slug: 'roopkund',
    title: 'Roopkund',
    region: 'Uttarakhand · Trishul massif, Chamoli',
    lat: 30.26,
    lng: 79.733,
    grade: 'grade-hard',
    gradeLabel: 'Strenuous',
    image: 'images/roopkund-lake.jpg',
    imageAlt: 'Roopkund, the glacial "Mystery Lake" beneath the Trishul massif',
    images: ['images/roopkund-lake.jpg'],
    imageCredit: 'Photo: Schwiki / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~53 km',
    cardStats: [
      { value: '5029m', label: 'Lake alt.' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'May–Jun, Sep–Oct', label: 'Season' },
    ],
    detailStats: [
      { value: '5029m', label: 'Lake alt.' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'May–Jun, Sep–Oct', label: 'Season' },
    ],
    desc: "The 'Mystery Lake' trek — high alpine meadows at Ali and Bedni Bugyal, a punishing summit-day push past scattered centuries-old human remains, and a shot at Junargali ridge with Trishul and Nanda Ghunti filling the skyline. The route and dates below are accurate; the photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'Route open for booking · DM @trekwith_g',
    durationDays: 7,
    maxAltitudeM: 5029,
    season: 'May–Jun, Sep–Oct',
    batchDates: ['May 22–28, 2027', 'Sep 18–24, 2027'],
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Lohajung → Didna village', body: 'A ~4 km warm-up walk to a terraced-farm village camp, easing into the altitude.' },
      { day: 'Day 2', title: 'Didna → Ali Bugyal / Bedni Bugyal', body: 'A ~10 km climb onto one of the largest alpine meadows in the Garhwal, camping at Bedni with Trishul in view.' },
      { day: 'Day 3', title: 'Bedni Bugyal → Bhagwabasa', body: 'A shorter ~6 km acclimatization day up to the last camp before the lake, on bare rock and late-season snow.' },
      { day: 'Day 4', title: 'Bhagwabasa → Roopkund (5,029m) → Junargali → Bhagwabasa', body: 'The summit push: a steep ~4 km to the lake and, conditions permitting, on to Junargali ridge, before returning to the same camp.' },
      { day: 'Day 5', title: 'Bhagwabasa → Bedni Bugyal', body: 'A long descent, roughly 10–11 km, back to the meadow camp.' },
      { day: 'Day 6', title: 'Bedni Bugyal → Wan → Lohajung', body: 'Descend through Wan village and drive back to Lohajung.' },
      { day: 'Day 7', title: 'Buffer / departure', body: 'Held in reserve for weather or snow conditions on the summit day.' },
    ],
  },
  'everest-base-camp': {
    slug: 'everest-base-camp',
    title: 'Everest Base Camp',
    region: 'Nepal · Khumbu, Sagarmatha National Park',
    lat: 28.0026,
    lng: 86.8528,
    grade: 'grade-hard',
    gradeLabel: 'Strenuous · Expedition',
    image: 'images/everest-base-camp-trail.jpg',
    imageAlt: 'The trail sign to Everest Base Camp near Gorak Shep, Khumbu',
    images: ['images/everest-base-camp-trail.jpg'],
    imageCredit: 'Photo: Michelle Welsch / Wikimedia Commons (CC BY-SA 3.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~130 km round trip',
    cardStats: [
      { value: '5364m', label: 'Base camp alt.' },
      { value: '12D / 11N', label: 'Duration' },
      { value: 'Mar–May, Sep–Dec', label: 'Season' },
    ],
    detailStats: [
      { value: '5364m', label: 'Base camp alt.' },
      { value: '12D / 11N', label: 'Duration' },
      { value: 'Mar–May, Sep–Dec', label: 'Season' },
    ],
    desc: "Our first Nepal route: the classic Khumbu teahouse trek from Lukla to the foot of the world's highest mountain, with a Kala Patthar sunrise thrown in. This route is newly added and still being scoped with a local operating partner — treat dates as provisional until confirmed. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 12,
    maxAltitudeM: 5364,
    season: 'Mar–May, Sep–Dec',
    included: [
      ...DEFAULT_INCLUDED.filter((item) => !item.includes('Camping')),
      'Teahouse lodging & meals on the trail',
      'Nepal TIMS card & Sagarmatha National Park permit',
      'Domestic flights, Kathmandu–Lukla–Kathmandu',
    ],
    excluded: [...DEFAULT_EXCLUDED, 'International flights & Nepal visa fee', 'Evacuation/rescue insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Kathmandu → Lukla → Phakding', body: 'A short scenic flight into Lukla (2,840m), then an easy ~3 hr walk down the Dudh Koshi valley to Phakding.' },
      { day: 'Day 2', title: 'Phakding → Namche Bazaar', body: 'A ~11 km climb into the Sherpa trading hub at 3,440m — the first proper acclimatization stop.' },
      { day: 'Day 3', title: 'Namche Bazaar — acclimatization day', body: 'A rest day with a day hike up to the Everest View Hotel or Khumjung for the first sight of the mountain itself.' },
      { day: 'Day 4', title: 'Namche → Tengboche', body: 'A ridge walk to the Tengboche monastery at 3,860m, with Ama Dablam dominating the skyline.' },
      { day: 'Day 5', title: 'Tengboche → Dingboche', body: 'Into drier, higher terrain, reaching Dingboche at 4,410m.' },
      { day: 'Day 6', title: 'Dingboche — acclimatization day', body: 'A day hike up Nangkartshang peak before pushing higher the next day.' },
      { day: 'Day 7', title: 'Dingboche → Lobuche', body: 'A ~9 km walk past the Khumbu glacier moraine to Lobuche at 4,940m.' },
      { day: 'Day 8', title: 'Lobuche → Gorak Shep → Everest Base Camp → Gorak Shep', body: 'Drop bags at Gorak Shep (5,164m), then push on to Everest Base Camp (5,364m) before returning to sleep at Gorak Shep.' },
      { day: 'Day 9', title: 'Gorak Shep → Kala Patthar → Pheriche', body: 'A pre-dawn climb to Kala Patthar (5,545m) for sunrise on Everest, then a long descent to Pheriche.' },
      { day: 'Day 10', title: 'Pheriche → Namche Bazaar', body: 'Retrace the trail back down to Namche.' },
      { day: 'Day 11', title: 'Namche → Lukla', body: 'The final ~19 km day back to the Lukla roadhead.' },
      { day: 'Day 12', title: 'Lukla → Kathmandu', body: 'Buffer built in for weather-delayed flights; used as a rest day in Kathmandu if the schedule holds.' },
    ],
  },
  'annapurna-base-camp': {
    slug: 'annapurna-base-camp',
    title: 'Annapurna Base Camp',
    region: 'Nepal · Annapurna Conservation Area',
    lat: 28.5308,
    lng: 83.8792,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/annapurna-base-camp-machhapuchre.jpg',
    imageAlt: 'Annapurna Base Camp lodges beneath Machhapuchhre (Fishtail), Annapurna Sanctuary',
    images: ['images/annapurna-base-camp-machhapuchre.jpg'],
    imageCredit: 'Photo: Nepalkismat / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~65 km round trip',
    cardStats: [
      { value: '4130m', label: 'Base camp alt.' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'Mar–May, Sep–Nov', label: 'Season' },
    ],
    detailStats: [
      { value: '4130m', label: 'Base camp alt.' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'Mar–May, Sep–Nov', label: 'Season' },
    ],
    desc: "A shorter, less extreme Nepal teahouse trek than EBC — through rhododendron forest and terraced villages into the Annapurna Sanctuary, a natural amphitheater ringed by 7,000m peaks. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 7,
    maxAltitudeM: 4130,
    season: 'Mar–May, Sep–Nov',
    included: [
      ...DEFAULT_INCLUDED.filter((item) => !item.includes('Camping')),
      'Teahouse lodging & meals on the trail',
      'Annapurna Conservation Area & TIMS permits',
    ],
    excluded: [...DEFAULT_EXCLUDED, 'International flights & Nepal visa fee', 'Evacuation/rescue insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Pokhara → Nayapul → Tikhedhunga', body: 'A drive to the Nayapul trailhead, then an easy ~5 km walk into the hills.' },
      { day: 'Day 2', title: 'Tikhedhunga → Ghorepani', body: 'A steep ~10 km climb — much of it stone steps — through rhododendron forest to Ghorepani at 2,860m.' },
      { day: 'Day 3', title: 'Poon Hill sunrise → Ghorepani → Chhomrong', body: 'A pre-dawn side trip to Poon Hill (3,210m) for an Annapurna/Dhaulagiri sunrise, then on to Chhomrong.' },
      { day: 'Day 4', title: 'Chhomrong → Himalaya / Deurali', body: 'Down into the Modi Khola gorge and back up through Bamboo and Dovan to Deurali at 3,230m.' },
      { day: 'Day 5', title: 'Deurali → Annapurna Base Camp → Bamboo', body: 'A short climb into the Sanctuary to the base camp at 4,130m, then a long same-day descent to Bamboo.' },
      { day: 'Day 6', title: 'Bamboo → Nayapul → Pokhara', body: 'Descend out of the gorge and drive back to Pokhara.' },
      { day: 'Day 7', title: 'Buffer / departure', body: 'Held in reserve for weather; a free day in Pokhara if the trail ran on schedule.' },
    ],
  },
  'poon-hill': {
    slug: 'poon-hill',
    title: 'Poon Hill',
    region: 'Nepal · Annapurna foothills, Ghorepani',
    lat: 28.4009,
    lng: 83.6996,
    grade: 'grade-easy',
    gradeLabel: 'Easy',
    image: 'images/poon-hill-sunrise.jpg',
    imageAlt: 'Dawn over Dhaulagiri seen from the Poon Hill viewpoint',
    images: ['images/poon-hill-sunrise.jpg'],
    imageCredit: 'Photo: Sajjan811 / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~33 km round trip',
    cardStats: [
      { value: '3210m', label: 'Viewpoint alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'Sep–May', label: 'Season' },
    ],
    detailStats: [
      { value: '3210m', label: 'Viewpoint alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'Sep–May', label: 'Season' },
    ],
    desc: "Our easiest Nepal route and a good first international trek — short teahouse days through Gurung villages to a sunrise viewpoint over Dhaulagiri and the Annapurna range. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 4,
    maxAltitudeM: 3210,
    season: 'Sep–May',
    included: [
      ...DEFAULT_INCLUDED.filter((item) => !item.includes('Camping')),
      'Teahouse lodging & meals on the trail',
      'Annapurna Conservation Area & TIMS permits',
    ],
    excluded: [...DEFAULT_EXCLUDED, 'International flights & Nepal visa fee', 'Evacuation/rescue insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Pokhara → Nayapul → Tikhedhunga', body: 'A drive to the trailhead, then an easy ~5 km walk in to the first overnight stop.' },
      { day: 'Day 2', title: 'Tikhedhunga → Ghorepani', body: 'A steep ~10 km stone-step climb through rhododendron forest to Ghorepani at 2,860m.' },
      { day: 'Day 3', title: 'Poon Hill sunrise → Tadapani', body: 'Pre-dawn walk up to Poon Hill (3,210m) for sunrise over Dhaulagiri and the Annapurnas, then on to Tadapani.' },
      { day: 'Day 4', title: 'Tadapani → Nayapul → Pokhara', body: 'Final descent through forest back to the roadhead and drive to Pokhara.' },
    ],
  },
  'langtang-valley': {
    slug: 'langtang-valley',
    title: 'Langtang Valley',
    region: 'Nepal · Langtang National Park',
    lat: 28.2138,
    lng: 85.5211,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/langtang-valley-trail.jpg',
    imageAlt: 'The trail through Langtang National Park toward Kyanjin Gompa',
    images: ['images/langtang-valley-trail.jpg'],
    imageCredit: 'Photo: Prakash Jamar Kattel / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~55 km round trip',
    cardStats: [
      { value: '3870m', label: 'Kyanjin Ri alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'Mar–May, Sep–Nov', label: 'Season' },
    ],
    detailStats: [
      { value: '3870m', label: 'Kyanjin Ri alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'Mar–May, Sep–Nov', label: 'Season' },
    ],
    desc: "The closest Himalayan teahouse trek to Kathmandu — a glacial valley walk beneath Langtang Lirung, through villages rebuilt since the 2015 earthquake, up to a yak-cheese factory at Kyanjin Gompa and a ridge viewpoint over a wall of 7,000m peaks. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 8,
    maxAltitudeM: 3870,
    season: 'Mar–May, Sep–Nov',
    included: [
      ...DEFAULT_INCLUDED.filter((item) => !item.includes('Camping')),
      'Teahouse lodging & meals on the trail',
      'Langtang National Park permit & TIMS card',
    ],
    excluded: [...DEFAULT_EXCLUDED, 'International flights & Nepal visa fee', 'Evacuation/rescue insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Kathmandu → Syabrubesi', body: 'A scenic ~7 hr drive out of the Kathmandu valley to the trailhead village at 1,460m.' },
      { day: 'Day 2', title: 'Syabrubesi → Lama Hotel', body: 'A ~12 km climb through forest along the Langtang Khola.' },
      { day: 'Day 3', title: 'Lama Hotel → Langtang village', body: 'Continue up the valley, passing through the area rebuilt after the 2015 earthquake, to Langtang village at 3,430m.' },
      { day: 'Day 4', title: 'Langtang village → Kyanjin Gompa', body: 'A short ~8 km day to Kyanjin Gompa at 3,870m, with the afternoon free to visit the monastery and cheese factory.' },
      { day: 'Day 5', title: 'Kyanjin Ri acclimatization & viewpoint', body: 'A morning climb up Kyanjin Ri (4,773m) for a full panorama of Langtang Lirung, then rest in the village.' },
      { day: 'Day 6', title: 'Kyanjin Gompa → Lama Hotel', body: 'Retrace the trail back down the valley.' },
      { day: 'Day 7', title: 'Lama Hotel → Syabrubesi', body: 'Final descent to the roadhead.' },
      { day: 'Day 8', title: 'Syabrubesi → Kathmandu', body: 'Drive back to Kathmandu; held as a buffer if the road is delayed.' },
    ],
  },
  'mardi-himal': {
    slug: 'mardi-himal',
    title: 'Mardi Himal',
    region: 'Nepal · Annapurna Conservation Area',
    lat: 28.4881,
    lng: 83.9308,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/mardi-himal-viewpoint.jpg',
    imageAlt: 'Trekkers on the ridge trail to Mardi Himal Base Camp, Annapurna region',
    images: ['images/mardi-himal-viewpoint.jpg'],
    imageCredit: 'Photo: Wojciech Kocot / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~44 km round trip',
    cardStats: [
      { value: '4500m', label: 'Base camp alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Mar–May, Sep–Dec', label: 'Season' },
    ],
    detailStats: [
      { value: '4500m', label: 'Base camp alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Mar–May, Sep–Dec', label: 'Season' },
    ],
    desc: "A newer, quieter alternative to the classic Annapurna routes — a steep ridge trail through rhododendron forest onto open alpine grassland, ending at a base camp with Machhapuchhre close enough to touch. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 6,
    maxAltitudeM: 4500,
    season: 'Mar–May, Sep–Dec',
    included: [
      ...DEFAULT_INCLUDED.filter((item) => !item.includes('Camping')),
      'Teahouse lodging & meals on the trail',
      'Annapurna Conservation Area permit & TIMS card',
    ],
    excluded: [...DEFAULT_EXCLUDED, 'International flights & Nepal visa fee', 'Evacuation/rescue insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Pokhara → Kande → Forest Camp', body: 'A short drive to the Kande trailhead, then a ~10 km climb into rhododendron forest.' },
      { day: 'Day 2', title: 'Forest Camp → Low Camp', body: 'Continue up the ridge through forest to Low Camp at 2,970m.' },
      { day: 'Day 3', title: 'Low Camp → High Camp', body: 'Break out of the treeline onto open ridge grassland, reaching High Camp at 3,580m with Machhapuchhre now dominating the view.' },
      { day: 'Day 4', title: 'High Camp → Mardi Himal Base Camp → Low Camp', body: 'A pre-dawn push to base camp (4,500m) for sunrise, then descend the same day back to Low Camp.' },
      { day: 'Day 5', title: 'Low Camp → Kande → Pokhara', body: 'Final descent to the trailhead and drive back to Pokhara.' },
      { day: 'Day 6', title: 'Buffer / departure', body: 'Held in reserve for weather on the ridge; a free day in Pokhara if the trail ran on schedule.' },
    ],
  },
  'manaslu-circuit': {
    slug: 'manaslu-circuit',
    title: 'Manaslu Circuit',
    region: 'Nepal · Manaslu Conservation Area',
    lat: 28.6667,
    lng: 84.7833,
    grade: 'grade-hard',
    gradeLabel: 'Strenuous · Expedition',
    image: 'images/manaslu-circuit-bimtang.jpg',
    imageAlt: 'Trekkers at Bimtang below the Manaslu range on the Manaslu Circuit',
    images: ['images/manaslu-circuit-bimtang.jpg'],
    imageCredit: 'Photo: Mohan K. Duwal / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~170 km',
    cardStats: [
      { value: '5106m', label: 'Larkya La' },
      { value: '15D / 14N', label: 'Duration' },
      { value: 'Mar–May, Sep–Nov', label: 'Season' },
    ],
    detailStats: [
      { value: '5106m', label: 'Larkya La' },
      { value: '15D / 14N', label: 'Duration' },
      { value: 'Mar–May, Sep–Nov', label: 'Season' },
    ],
    desc: "A restricted-area circuit around the eighth-highest mountain on earth — quieter and wilder than the Annapurna or Everest trails, climbing through Tibetan-influenced villages in the upper valley before crossing the high, glaciated Larkya La. Requires a restricted-area permit and a licensed guide by law. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 15,
    maxAltitudeM: 5106,
    season: 'Mar–May, Sep–Nov',
    included: [
      ...DEFAULT_INCLUDED.filter((item) => !item.includes('Camping')),
      'Teahouse lodging & meals on the trail',
      'Manaslu restricted-area permit, MCAP & ACAP fees',
    ],
    excluded: [...DEFAULT_EXCLUDED, 'International flights & Nepal visa fee', 'Evacuation/rescue insurance'],
    itinerary: [
      { day: 'Day 1', title: 'Kathmandu → Soti Khola', body: 'A long drive out to the trailhead at 700m.' },
      { day: 'Day 2', title: 'Soti Khola → Machha Khola', body: 'A ~14 km walk along the Budhi Gandaki river.' },
      { day: 'Day 3', title: 'Machha Khola → Jagat', body: 'Continue upriver through forest and small villages, entering the restricted area at Jagat.' },
      { day: 'Day 4', title: 'Jagat → Deng', body: 'The valley narrows into a gorge as the trail climbs toward Deng.' },
      { day: 'Day 5', title: 'Deng → Namrung', body: 'Cross into the upper, more Tibetan-influenced part of the valley.' },
      { day: 'Day 6', title: 'Namrung → Samagaon', body: 'Reach Samagaon at 3,530m, the main acclimatization base beneath Manaslu itself.' },
      { day: 'Day 7', title: 'Samagaon — acclimatization day', body: 'A day hike up to Manaslu Base Camp or Birendra Lake before pushing higher.' },
      { day: 'Day 8', title: 'Samagaon → Samdo', body: 'A short ~7 km day to the last village before the pass, close to the Tibet border.' },
      { day: 'Day 9', title: 'Samdo — acclimatization day', body: 'A rest day with an optional side trip toward the Tibet border ridge.' },
      { day: 'Day 10', title: 'Samdo → Dharamsala (Larkya Phedi)', body: 'A short move up to the last camp before the pass, at 4,470m.' },
      { day: 'Day 11', title: 'Dharamsala → Larkya La (5,106m) → Bimtang', body: 'The long summit day: a pre-dawn crossing of the pass, then a steep descent to Bimtang with Manaslu behind and the Annapurnas ahead.' },
      { day: 'Day 12', title: 'Bimtang → Gho', body: 'Descend into forest on the western side of the pass.' },
      { day: 'Day 13', title: 'Gho → Dharapani', body: 'Continue down to Dharapani, joining the lower Annapurna Circuit trail.' },
      { day: 'Day 14', title: 'Dharapani → Kathmandu (via Besisahar)', body: 'A long drive back to Kathmandu.' },
      { day: 'Day 15', title: 'Buffer / departure', body: 'Held in reserve for weather at the pass or road delays.' },
    ],
  },
  'kashmir-great-lakes': {
    slug: 'kashmir-great-lakes',
    title: 'Kashmir Great Lakes',
    region: 'Jammu & Kashmir · Sonamarg to Naranag',
    lat: 34.3,
    lng: 75.3,
    grade: 'grade-mod',
    gradeLabel: 'Moderate – Difficult',
    image: 'images/kashmir-great-lakes.jpg',
    imageAlt: 'Vishansar and Kishansar twin alpine lakes on the Kashmir Great Lakes trek',
    images: ['images/kashmir-great-lakes.jpg'],
    imageCredit: 'Photo: Critical koshur / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~72 km',
    cardStats: [
      { value: '4191m', label: 'Gadsar Pass' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    detailStats: [
      { value: '4191m', label: 'Gadsar Pass' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    desc: "Widely rated India's finest alpine trek — a string of seven high-altitude lakes (Vishansar, Kishansar, Gadsar, Satsar, Gangbal) strung across three passes in a single monsoon-window route. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 7,
    maxAltitudeM: 4191,
    season: 'Jul–Sep',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Sonamarg → Shekdur', body: 'An easy ~8 km warm-up walk along the Nichnai valley to the first forest camp.' },
      { day: 'Day 2', title: 'Shekdur → Nichnai', body: 'An ~11 km climb toward Nichnai pass, camping just below the treeline.' },
      { day: 'Day 3', title: 'Nichnai → Vishansar Lake', body: 'Cross Nichnai Pass (~3,800m) and descend to camp beside Vishansar, the first of the twin lakes, ~12 km.' },
      { day: 'Day 4', title: 'Vishansar → Gadsar via Gadsar Pass (4,191m)', body: 'The hardest and highest day, ~14 km, crossing Gadsar Pass with views over Kishansar before dropping to Gadsar Lake.' },
      { day: 'Day 5', title: 'Gadsar → Satsar', body: 'A gentler ~10 km day past a chain of smaller lakes to camp at Satsar.' },
      { day: 'Day 6', title: 'Satsar → Gangbal Lake via Zaj Pass', body: 'Cross Zaj Pass (~4,100m) and camp at Gangbal, beneath Mt Harmukh, ~12 km.' },
      { day: 'Day 7', title: 'Gangbal → Naranag → Srinagar', body: 'A ~13 km descent to the Naranag roadhead, then drive out.' },
    ],
  },
  'tarsar-marsar': {
    slug: 'tarsar-marsar',
    title: 'Tarsar Marsar',
    region: 'Jammu & Kashmir · Aru, Anantnag',
    lat: 34.15,
    lng: 75.25,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/tarsar-lake.jpg',
    imageAlt: 'Tarsar Lake beneath the Kolahoi range, Kashmir',
    images: ['images/tarsar-lake.jpg'],
    imageCredit: 'Photo: Irfanaru / Wikimedia Commons (CC BY-SA 3.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~48 km',
    cardStats: [
      { value: '4085m', label: 'Jasser Pass' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    detailStats: [
      { value: '4085m', label: 'Jasser Pass' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    desc: "Two teardrop lakes separated by a single ridge — Tarsar on one side, Marsar on the other, both beneath the Kolahoi glacier. Quieter than the Great Lakes route and just as dramatic. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 6,
    maxAltitudeM: 4085,
    season: 'Jul–Sep',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Aru → Lidderwat', body: 'An ~11 km walk through pine forest along the Lidder river.' },
      { day: 'Day 2', title: 'Lidderwat → Shekwas', body: 'A ~9 km climb into higher meadow country.' },
      { day: 'Day 3', title: 'Shekwas → Tarsar Lake', body: 'A short ~6 km day to camp right beside Tarsar, with Kolahoi filling the skyline.' },
      { day: 'Day 4', title: 'Tarsar → Sundersar via Jasser Pass (4,085m)', body: 'Cross the high pass between the two lake systems, ~9 km, to camp at Sundersar.' },
      { day: 'Day 5', title: 'Sundersar → Marsar Lake → Homwas', body: 'A short side visit to Marsar\'s viewpoint, then a ~11 km descent to Homwas.' },
      { day: 'Day 6', title: 'Homwas → Aru → Pahalgam', body: 'Final ~9 km walk out and drive back to Pahalgam.' },
    ],
  },
  'rupin-pass': {
    slug: 'rupin-pass',
    title: 'Rupin Pass',
    region: 'Himachal Pradesh–Uttarakhand · Dhaula to Sangla',
    lat: 31.15,
    lng: 78.15,
    grade: 'grade-hard',
    gradeLabel: 'Difficult',
    image: 'images/rupin-pass.jpg',
    imageAlt: 'High-altitude terrain on the Rupin Pass route toward Sangla',
    images: ['images/rupin-pass.jpg'],
    imageCredit: 'Photo: Nikitaparwani / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~52 km',
    cardStats: [
      { value: '4650m', label: 'Pass alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'May–Jun, Sep–Oct', label: 'Season' },
    ],
    detailStats: [
      { value: '4650m', label: 'Pass alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'May–Jun, Sep–Oct', label: 'Season' },
    ],
    desc: "One of the most varied crossings in the Himalaya — waterfall crossings, hanging villages, a near-vertical snow wall below the pass, and a final drop into Himachal's Sangla valley. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 8,
    maxAltitudeM: 4650,
    season: 'May–Jun, Sep–Oct',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Dhaula → Sewa', body: 'A gentle ~6 km start along the Rupin river.' },
      { day: 'Day 2', title: 'Sewa → Jhaka', body: 'An ~8 km walk past a waterfall crossing to the last inhabited village on the route.' },
      { day: 'Day 3', title: 'Jhaka → Saruwas Thatch', body: 'Forest gives way to open meadow over ~8 km.' },
      { day: 'Day 4', title: 'Saruwas Thatch → Dhanderas Thatch', body: 'A short ~6 km day with the first close views of the pass headwall.' },
      { day: 'Day 5', title: 'Dhanderas Thatch → Upper Waterfall Camp', body: 'A deliberately short ~5 km acclimatization day at the base of the final climb.' },
      { day: 'Day 6', title: 'Upper Waterfall Camp → Rupin Pass (4,650m) → Ronti Gad', body: 'The crossing day: a steep snow wall to the pass, then descent into Himachal, ~9 km.' },
      { day: 'Day 7', title: 'Ronti Gad → Sangla Kanda → Sangla', body: 'Final ~10 km descent to the roadhead.' },
      { day: 'Day 8', title: 'Buffer / departure', body: 'Held in reserve for weather on the pass; used for the drive out if the trail ran on schedule.' },
    ],
  },
  'pin-parvati-pass': {
    slug: 'pin-parvati-pass',
    title: 'Pin Parvati Pass',
    region: 'Himachal Pradesh · Parvati to Pin Valley crossing',
    lat: 32.02,
    lng: 77.62,
    grade: 'grade-hard',
    gradeLabel: 'Difficult · Expedition',
    image: 'images/pin-parvati-mantalai-lake.jpg',
    imageAlt: 'Mantalai Lake, the last camp before the Pin Parvati Pass crossing',
    images: ['images/pin-parvati-mantalai-lake.jpg'],
    imageCredit: 'Photo: Bharatkaistha / Wikimedia Commons (CC BY-SA 4.0) — reference image of Mantalai Lake, the last camp before the pass, not the pass itself; not from a TrekwithG batch',
    distanceKm: '~110 km',
    cardStats: [
      { value: '5319m', label: 'Pass alt.' },
      { value: '11D / 10N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    detailStats: [
      { value: '5319m', label: 'Pass alt.' },
      { value: '11D / 10N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    desc: "One of the longest and most technical crossings we'd consider running — glacier travel and a genuine expedition feel linking the hot-spring Parvati valley to high, dry Spiti. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above shows Mantalai Lake, the last camp before the pass, not the pass itself, and is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 11,
    maxAltitudeM: 5319,
    season: 'Jul–Sep',
    included: [...DEFAULT_INCLUDED, 'Glacier crossing gear & rope-fixing crew'],
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Barshaini → Kalga → Kheerganga', body: 'Trailhead walk-in through the lower Parvati valley, ~9 km.' },
      { day: 'Day 2', title: 'Kheerganga → Tunda Bhuj', body: 'Deeper into forest along the Parvati river, ~11 km.' },
      { day: 'Day 3', title: 'Tunda Bhuj → Thakur Kuan', body: 'A ~10 km walk further up the valley.' },
      { day: 'Day 4', title: 'Thakur Kuan → Odi Thach', body: 'Tree line thins out over ~9 km.' },
      { day: 'Day 5', title: 'Odi Thach → Mantalai Lake', body: 'Arrive at the sacred source lake of the Parvati river, ~8 km, the last camp before the pass.' },
      { day: 'Day 6', title: 'Mantalai — acclimatization & gear check', body: 'Rest day; ropes and glacier gear checked ahead of the crossing.' },
      { day: 'Day 7', title: 'Mantalai → Pin Parvati Pass (5,319m) → Pin Valley camp', body: 'The big crossing day — glacier travel to the pass, then a long descent into Spiti, ~14 km.' },
      { day: 'Day 8', title: 'Pin Valley camp → Mudh village', body: 'Descend into the first Spiti village, ~12 km.' },
      { day: 'Day 9', title: 'Mudh → Kaza', body: 'Drive out to Kaza for the first proper rest since Mantalai.' },
      { day: 'Day 10', title: 'Buffer day', body: 'Held in reserve for weather or pace on the crossing.' },
      { day: 'Day 11', title: 'Departure from Kaza', body: 'Onward drive to Manali or Shimla.' },
    ],
  },
  'bhrigu-lake': {
    slug: 'bhrigu-lake',
    title: 'Bhrigu Lake',
    region: 'Himachal Pradesh · Above Gulaba, Manali',
    lat: 32.28,
    lng: 77.33,
    grade: 'grade-easy',
    gradeLabel: 'Easy – Moderate',
    image: 'images/bhrigu-lake.jpg',
    imageAlt: 'Bhrigu Lake and surrounding alpine terrain, Himachal Pradesh',
    images: ['images/bhrigu-lake.jpg'],
    imageCredit: 'Photo: Ahmad Faiz Mustafa / Wikimedia Commons (CC BY 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~20 km',
    cardStats: [
      { value: '4300m', label: 'Lake alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'May–Jun, Sep–Oct', label: 'Season' },
    ],
    detailStats: [
      { value: '4300m', label: 'Lake alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'May–Jun, Sep–Oct', label: 'Season' },
    ],
    desc: "A short drive from Manali gets you to open meadow fast, and from there it's a quick climb to a high glacial lake that stays part-frozen well into summer. Good weekend option for a first high-altitude camp. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 4,
    maxAltitudeM: 4300,
    season: 'May–Jun, Sep–Oct',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Manali → Gulaba → Rola Kholi', body: 'A short drive to the roadhead then an easy ~5 km climb to the first meadow camp.' },
      { day: 'Day 2', title: 'Rola Kholi → Bhrigu Lake → Khanidhar', body: 'Climb to the lake at 4,300m, then descend to a lower camp the same day, ~11 km.' },
      { day: 'Day 3', title: 'Khanidhar → Gulaba → Manali', body: 'Descend to the roadhead and drive back, ~6 km on foot.' },
      { day: 'Day 4', title: 'Buffer / departure', body: 'Held in reserve for weather at the lake.' },
    ],
  },
  'deoriatal-chandrashila': {
    slug: 'deoriatal-chandrashila',
    title: 'Deoriatal–Chandrashila',
    region: 'Uttarakhand · Sari to Chopta–Tungnath',
    lat: 30.53,
    lng: 79.33,
    grade: 'grade-easy',
    gradeLabel: 'Easy – Moderate',
    image: 'images/deoriatal-chandrashila.jpg',
    imageAlt: 'Chaukhamba peak reflected in Deoria Tal lake',
    images: ['images/deoriatal-chandrashila.jpg'],
    imageCredit: 'Photo: Senthilnath G T / Wikimedia Commons (CC BY-SA 3.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~20 km',
    cardStats: [
      { value: '3680m', label: 'Summit alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'Mar–Jun, Sep–Dec', label: 'Season' },
    ],
    detailStats: [
      { value: '3680m', label: 'Summit alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'Mar–Jun, Sep–Dec', label: 'Season' },
    ],
    desc: "A lake with one of the best mountain reflections in the Garhwal, followed by a ridge walk past the highest Shiva temple in the world (Tungnath) to a 360° summit at Chandrashila. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 4,
    maxAltitudeM: 3680,
    season: 'Mar–Jun, Sep–Dec',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Sari → Deoriatal', body: 'A short ~3 km climb to camp beside the lake, with Chaukhamba reflected on clear mornings.' },
      { day: 'Day 2', title: 'Deoriatal → Rohini Bugyal / Chopta', body: 'A ~10 km ridge walk through meadow to Chopta.' },
      { day: 'Day 3', title: 'Chopta → Tungnath → Chandrashila (3,680m) → Chopta', body: 'A ~8 km round trip past the Tungnath temple to the summit and back.' },
      { day: 'Day 4', title: 'Departure from Chopta', body: 'Onward drive to Rishikesh or Haridwar.' },
    ],
  },
  'nag-tibba': {
    slug: 'nag-tibba',
    title: 'Nag Tibba',
    region: 'Uttarakhand · Above Pantwari, Mussoorie range',
    lat: 30.45,
    lng: 78.25,
    grade: 'grade-easy',
    gradeLabel: 'Easy',
    image: 'images/nag-tibba.jpg',
    imageAlt: 'Camping ground and Mussoorie valley view from the Nag Tibba summit trail',
    images: ['images/nag-tibba.jpg'],
    imageCredit: 'Photo: Ashish Gupta / Wikimedia Commons (CC BY 2.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~15 km',
    cardStats: [
      { value: '3022m', label: 'Summit alt.' },
      { value: '2D / 1N', label: 'Duration' },
      { value: 'Oct–Jun', label: 'Season' },
    ],
    detailStats: [
      { value: '3022m', label: 'Summit alt.' },
      { value: '2D / 1N', label: 'Duration' },
      { value: 'Oct–Jun', label: 'Season' },
    ],
    desc: "The closest real summit to Delhi/Dehradun on a weekend — a steep climb through oak and rhododendron to a ridge camp by an old temple, then a short sunrise push to the highest point in the Nag Tibba range. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 2,
    maxAltitudeM: 3022,
    season: 'Oct–Jun',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Pantwari → Nag Tibba camp', body: 'A steep ~7 km climb through oak and rhododendron forest to a ridge camp near the Nag Tibba temple.' },
      { day: 'Day 2', title: 'Summit (3,022m) → Pantwari', body: 'A short pre-dawn push to the top for sunrise over the Bandarpunch range, then descend the same ~7 km back down.' },
    ],
  },
  'kuari-pass': {
    slug: 'kuari-pass',
    title: 'Kuari Pass',
    region: 'Uttarakhand · Joshimath–Auli, Nanda Devi Sanctuary rim',
    lat: 30.45,
    lng: 79.63,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/kuari-pass.jpg',
    imageAlt: 'Alpine meadow (bugyal) landscape at Kuari Pass, Uttarakhand',
    images: ['images/kuari-pass.jpg'],
    imageCredit: 'Photo: Vaibhav78545 / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~33 km',
    cardStats: [
      { value: '3860m', label: 'Pass alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Sep–Jun', label: 'Season' },
    ],
    detailStats: [
      { value: '3860m', label: 'Pass alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Sep–Jun', label: 'Season' },
    ],
    desc: "Known as the 'Curzon Trail' — a long balcony walk with Nanda Devi, Dronagiri and Kamet lined up across the valley almost the whole way. Works as a winter snow trek or a green-season ridge walk. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 6,
    maxAltitudeM: 3860,
    season: 'Sep–Jun',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Joshimath/Auli → Gulling Top', body: 'A ~6 km climb out of Auli into forest and meadow.' },
      { day: 'Day 2', title: 'Gulling Top → Khullara', body: 'A ~5 km ridge walk to a meadow camp with the first big Nanda Devi views.' },
      { day: 'Day 3', title: 'Khullara → Kuari Pass (3,860m) → Khullara', body: 'A ~10 km round trip to the pass and back, with Dronagiri and Kamet across the valley.' },
      { day: 'Day 4', title: 'Khullara → Tali forest camp', body: 'A ~7 km descent into forest.' },
      { day: 'Day 5', title: 'Tali → Joshimath', body: 'Final ~5 km walk out to the roadhead.' },
      { day: 'Day 6', title: 'Buffer / departure', body: 'Held in reserve for weather; used for the drive out if the trail ran on schedule.' },
    ],
  },
  'dayara-bugyal': {
    slug: 'dayara-bugyal',
    title: 'Dayara Bugyal',
    region: 'Uttarakhand · Above Barsu/Raithal, Uttarkashi',
    lat: 30.83,
    lng: 78.53,
    grade: 'grade-easy',
    gradeLabel: 'Easy',
    image: 'images/dayara-bugyal.jpg',
    imageAlt: 'Trail en route to Dayara Bugyal near Gui camp, Uttarkashi',
    images: ['images/dayara-bugyal.jpg'],
    imageCredit: 'Photo: Satdeep Gill / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~18 km',
    cardStats: [
      { value: '3048m', label: 'Meadow alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'Dec–Apr, May–Jun', label: 'Season' },
    ],
    detailStats: [
      { value: '3048m', label: 'Meadow alt.' },
      { value: '4D / 3N', label: 'Duration' },
      { value: 'Dec–Apr, May–Jun', label: 'Season' },
    ],
    desc: "One of the largest high-altitude meadows in the Garhwal — a gentle climb through deodar forest opens onto rolling grassland with Bandarpunch filling the horizon. Snow-covered and quiet in winter, wildflower-green in early summer. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 4,
    maxAltitudeM: 3048,
    season: 'Dec–Apr, May–Jun',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Barsu → Gui camp', body: 'A ~6 km climb through deodar forest to a camp at the meadow\'s edge.' },
      { day: 'Day 2', title: 'Gui → Dayara Bugyal (3,048m) → Chilapada', body: 'A full day out across the meadow with Bandarpunch views, then on to a lower camp, ~8 km.' },
      { day: 'Day 3', title: 'Chilapada → Barsu', body: 'A ~7 km descent back to the roadhead.' },
      { day: 'Day 4', title: 'Buffer / departure', body: 'Held in reserve for snow conditions; used for the drive out if the trail ran on schedule.' },
    ],
  },
  goechala: {
    slug: 'goechala',
    title: 'Goechala',
    region: 'Sikkim · Yuksom, Kangchenjunga National Park',
    lat: 27.7,
    lng: 88.15,
    grade: 'grade-hard',
    gradeLabel: 'Difficult',
    image: 'images/goechala.jpg',
    imageAlt: 'Himalayan trekking landscape on the Goechala trail, Sikkim',
    images: ['images/goechala.jpg'],
    imageCredit: 'Photo: Magicktrips.com / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~90 km',
    cardStats: [
      { value: '4940m', label: 'Goecha La view' },
      { value: '9D / 8N', label: 'Duration' },
      { value: 'Mar–May, Oct–Nov', label: 'Season' },
    ],
    detailStats: [
      { value: '4940m', label: 'Goecha La view' },
      { value: '9D / 8N', label: 'Duration' },
      { value: 'Mar–May, Oct–Nov', label: 'Season' },
    ],
    desc: "The closest most trekkers get to Kangchenjunga, the world's third-highest peak, without a mountaineering permit — rhododendron forest, the Dzongri ridge, and a dawn viewpoint at Goecha La that's worth every one of the nine days. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 9,
    maxAltitudeM: 4940,
    season: 'Mar–May, Oct–Nov',
    included: [...DEFAULT_INCLUDED, 'Sikkim restricted-area permit (Kangchenjunga National Park)'],
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Yuksom → Sachen', body: 'A ~10 km walk into Kangchenjunga National Park forest.' },
      { day: 'Day 2', title: 'Sachen → Tshoka', body: 'A ~7 km climb to a Tibetan settlement camp.' },
      { day: 'Day 3', title: 'Tshoka → Dzongri', body: 'A ~10 km climb above the treeline to the main acclimatization stop.' },
      { day: 'Day 4', title: 'Dzongri — acclimatization day', body: 'Rest day with a side hike up Dzongri Top for the first Kangchenjunga views.' },
      { day: 'Day 5', title: 'Dzongri → Thansing', body: 'A ~10 km walk into the high Prek Chu valley.' },
      { day: 'Day 6', title: 'Thansing → Lamuney', body: 'A short ~3 km day to position for the viewpoint push.' },
      { day: 'Day 7', title: 'Lamuney → Goecha La viewpoint (4,940m) → Kokchurang', body: 'A pre-dawn push to the viewpoint for Kangchenjunga at sunrise, then a long ~12 km descent.' },
      { day: 'Day 8', title: 'Kokchurang → Tshoka', body: 'Retrace the route down, ~11 km.' },
      { day: 'Day 9', title: 'Tshoka → Yuksom', body: 'Final ~15 km walk out and departure.' },
    ],
  },
  'sandakphu-phalut': {
    slug: 'sandakphu-phalut',
    title: 'Sandakphu–Phalut',
    region: 'West Bengal–Sikkim border · Singalila ridge',
    lat: 27.11,
    lng: 88.0,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/sandakphu-sunrise.jpg',
    imageAlt: 'Sunrise panorama from Sandakphu over Kangchenjunga, Jannu and Pandim',
    images: ['images/sandakphu-sunrise.jpg'],
    imageCredit: 'Photo: Mamtarivonkar / Wikimedia Commons (CC BY-SA 4.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~65 km',
    cardStats: [
      { value: '3636m', label: 'Summit alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Oct–Dec, Mar–Apr', label: 'Season' },
    ],
    detailStats: [
      { value: '3636m', label: 'Summit alt.' },
      { value: '6D / 5N', label: 'Duration' },
      { value: 'Oct–Dec, Mar–Apr', label: 'Season' },
    ],
    desc: "A ridge walk along the Nepal border to the one viewpoint in India where four of the world's five highest peaks — Everest, Kangchenjunga, Lhotse and Makalu — line up on a clear morning. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 6,
    maxAltitudeM: 3636,
    season: 'Oct–Dec, Mar–Apr',
    included: DEFAULT_INCLUDED,
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Maneybhanjang → Tumling', body: 'An ~11 km climb along the Nepal-border ridge road and trail.' },
      { day: 'Day 2', title: 'Tumling → Kalipokhri → Sandakphu (3,636m)', body: 'A ~15 km day to the highest point in West Bengal, with sunset views over five ranges.' },
      { day: 'Day 3', title: 'Sandakphu → Phalut', body: 'The longest day, ~21 km along the open ridge with Kangchenjunga in view most of the way.' },
      { day: 'Day 4', title: 'Phalut → Gorkhey', body: 'A ~15 km descent through rhododendron forest.' },
      { day: 'Day 5', title: 'Gorkhey → Rammam → Rimbik', body: 'Final ~15 km walk out to the roadhead.' },
      { day: 'Day 6', title: 'Departure from Rimbik', body: 'Onward drive to Darjeeling or NJP.' },
    ],
  },
  'markha-valley': {
    slug: 'markha-valley',
    title: 'Markha Valley',
    region: 'Ladakh · Hemis National Park',
    lat: 34.0,
    lng: 77.5,
    grade: 'grade-mod',
    gradeLabel: 'Moderate',
    image: 'images/markha-valley-kongmaru-la.jpg',
    imageAlt: 'View from Kongmaru La pass, the endpoint of the Markha Valley trek',
    images: ['images/markha-valley-kongmaru-la.jpg'],
    imageCredit: 'Photo: Chris Hunkeler / Wikimedia Commons (CC BY-SA 2.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~65 km',
    cardStats: [
      { value: '5150m', label: 'Kongmaru La' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'Jun–Sep', label: 'Season' },
    ],
    detailStats: [
      { value: '5150m', label: 'Kongmaru La' },
      { value: '7D / 6N', label: 'Duration' },
      { value: 'Jun–Sep', label: 'Season' },
    ],
    desc: "Ladakh's classic trans-Himalayan trek — a river-valley walk through mud-brick villages and barley fields inside Hemis National Park, finishing with a high pass crossing at Kongmaru La. Newly added and still being scoped with a local operating partner; treat dates as provisional. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest',
    durationDays: 7,
    maxAltitudeM: 5150,
    season: 'Jun–Sep',
    included: [...DEFAULT_INCLUDED, 'Hemis National Park permit'],
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Leh — acclimatization day', body: 'A full rest day at altitude before trekking begins, non-negotiable at 3,500m.' },
      { day: 'Day 2', title: 'Chilling → Skiu', body: 'A ~12 km walk along the Zanskar/Markha river confluence.' },
      { day: 'Day 3', title: 'Skiu → Markha village', body: 'A long ~19 km day up the valley past mud-brick villages and barley fields.' },
      { day: 'Day 4', title: 'Markha → Hankar', body: 'A ~12 km walk with the first views toward Nimaling.' },
      { day: 'Day 5', title: 'Hankar → Nimaling', body: 'A ~10 km climb to a high pasture camp below Kang Yatse.' },
      { day: 'Day 6', title: 'Nimaling → Kongmaru La (5,150m) → Chogdo', body: 'The crossing day, ~13 km, over the trek\'s highest point and down into the Shang valley.' },
      { day: 'Day 7', title: 'Chogdo → Shang Sumdo → Leh', body: 'Final ~8 km walk out and drive back to Leh.' },
    ],
  },
  'stok-kangri': {
    slug: 'stok-kangri',
    title: 'Stok Kangri',
    region: 'Ladakh · Stok village, Hemis National Park',
    lat: 33.93,
    lng: 77.71,
    grade: 'grade-hard',
    gradeLabel: 'Difficult · Peak climb',
    image: 'images/stok-kangri.jpg',
    imageAlt: 'Zanskar range and Stok Kangri peak seen from Leh',
    images: ['images/stok-kangri.jpg'],
    imageCredit: 'Photo: DanHobley / Wikimedia Commons (CC BY-SA 3.0) — reference image, not from a TrekwithG batch',
    distanceKm: '~26 km + summit push',
    cardStats: [
      { value: '6153m', label: 'Summit alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    detailStats: [
      { value: '6153m', label: 'Summit alt.' },
      { value: '8D / 7N', label: 'Duration' },
      { value: 'Jul–Sep', label: 'Season' },
    ],
    desc: "Ladakh's best-known trekking peak — a non-technical but genuinely high summit above Leh, with a pre-dawn glacier walk and a short fixed-rope section near the top. Note: Ladakh's Wildlife Department has periodically restricted or closed Stok Kangri to climbers in recent years pending an access policy — treat this as a reference route to register interest in, not a confirmed permit. Newly added and still being scoped with a local operating partner. The photo above is a reference image, not from a TrekwithG batch yet.",
    note: 'In scoping — DM @trekwith_g to register interest (permit status pending)',
    durationDays: 8,
    maxAltitudeM: 6153,
    season: 'Jul–Sep',
    included: [...DEFAULT_INCLUDED, 'Summit gear (crampons, ice axe, fixed rope) & climbing guide'],
    excluded: DEFAULT_EXCLUDED,
    itinerary: [
      { day: 'Day 1', title: 'Leh — acclimatization day', body: 'A full rest day at altitude before any trekking begins.' },
      { day: 'Day 2', title: 'Leh → Stok village → Chang Ma', body: 'Drive to the trailhead then a ~7 km walk into the Stok valley.' },
      { day: 'Day 3', title: 'Chang Ma → Mankarmo (Base Camp)', body: 'A ~9 km climb to base camp below the peak.' },
      { day: 'Day 4', title: 'Base camp — rest & gear briefing', body: 'Acclimatization day with a crampon/ice-axe refresher for the summit push.' },
      { day: 'Day 5', title: 'Base camp → Summit (6,153m) → Base camp', body: 'Pre-dawn start for the glacier crossing and summit ridge, back to base camp the same (long) day.' },
      { day: 'Day 6', title: 'Base camp → Stok village → Leh', body: 'Descend and drive back to Leh.' },
      { day: 'Day 7', title: 'Buffer day', body: 'Held in reserve for weather or an extra acclimatization day.' },
      { day: 'Day 8', title: 'Departure from Leh', body: 'Used as a rest day in Leh if the schedule holds.' },
    ],
  },
  custom: {
    slug: 'custom',
    title: 'Build your own',
    region: 'Any region · with Moksha Adventures on select routes',
    grade: 'grade-hard',
    gradeLabel: 'Custom · Expedition',
    image: 'images/ladakh-basecamp.jpg',
    imageAlt: 'Trekking camp near Tso Kar, Ladakh',
    images: [
      'images/ladakh-basecamp.jpg',
      'images/ladakh-tsokar-reflections.jpg',
      'images/ladakh-tsokar-salt.jpg',
    ],
    cardStats: [
      { value: 'Flexible', label: 'Duration' },
      { value: '4+', label: 'Min. group' },
    ],
    detailStats: [
      { value: 'Flexible', label: 'Duration' },
      { value: '4+', label: 'Min. group' },
    ],
    desc: "Corporate offsites, college groups, or a summit you've had on a list for years — we'll scope route, permits and crew for a private departure.",
    note: 'Start with a DM · @trekwith_g',
    season: 'Any (route-dependent)',
    itineraryHeading: 'How it works',
    itineraryEyebrow: 'Custom departures',
    itineraryNote: 'No fixed dates — every custom trip starts with a call.',
    itinerary: [
      { day: 'Step 1', title: 'Discovery call', body: 'Tell us group size, dates, fitness level and what you actually want out of the trip — summit, scenery, or just time off-grid.' },
      { day: 'Step 2', title: 'Route & permit scoping', body: 'We shortlist 2–3 route options against your dates and sort forest/wildlife permits where the region needs them.' },
      { day: 'Step 3', title: 'Crew & logistics', body: 'Guides, cooks and porters are booked, gear-on-rent sorted, and a day-by-day plan is shared before you pay anything.' },
      { day: 'Step 4', title: 'On trail', body: 'Same small-batch rules as our fixed departures — rest days above 3,200m, a hard turn-back call if pace slips.' },
    ],
  },
};

export const TREK_SLUGS = Object.keys(TREKS);

export function getTrek(slug: string): Trek | undefined {
  return TREKS[slug];
}

export function getAllTreks(): Trek[] {
  return TREK_SLUGS.map((slug) => TREKS[slug]);
}
